{%- set greeting = salt['hello.greet']('Minion') -%}

greeting_message:
  test.configurable_test_state:
    - name: {{ greeting }}
    - result: true
    - comment: "Greeting generated by saltext-hello extension"
