name: foo
version: 0.1.1
description: Foo formula
maintainers:
  - name: Developer
    email: dev@example.com

dependencies:
  - name: bar
    version: ">=1.0.0"

salt:
  min_version: '3006'
  max_version: '3009'