project: example-project
version: 1.0.0
vendor_dir: vendor

repositories:
  - name: local
    url: file:///srv/salt-repo/

dependencies:
  # foo depends on bar, so 'salt-bundle project update' will install both
  foo: "^0.1.0"
